import bcrypt from 'bcryptjs';
const data = {
    users: [
        {
            name: 'Garvit',
            email: 'admin@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name: 'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,   
        },
    ],
    products:[
        {
            name:'Daksh-Prot',
            category:'Proteins',
            image:'/Images/Product1.jpg',
            image1:'/Images/Product1(1).png',
            image2:'/Images/Product1.png',
            price:345,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Health+ Orange-Flavour',
            category:'Energy Booster',
            image:'/Images/Product2.jpg',
            image1:'/Images/Product2(1).png',
            image2:'/Images/Product2(2).png',
            price:76,
            countInStock: 20,
            brand:'Sarthi Ayurveda',
            rating:4.0,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Amar Churan',
            category:'Digestive Tonic',
            image:'/Images/Product3.jpg',
            image1:'/Images/Product3(1).png',
            image2:'/Images/Product3(2).png',
            price:124,
            countInStock: 20,
            brand:'Sarthi Ayurveda',
            rating:4.8,
            numReviews:17,
            description:'high quality product',
        },
        {
            name:'Kuffna',
            category:'Cough Remedy',
            image:'/Images/Product4.jpg',
            image1:'/Images/Product4(1).png',
            image2:'/Images/Product4(2).png',
            price:117,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Sarliv 4G',
            category:'Digestive Tonic',
            image:'/Images/Product5.jpg',
            image1:'/Images/Product5(1).png',
            image2:'/Images/Product5(2).png',
            price:155,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:"Happy 7 Day's",
            category:'Women Health Restorative Tonic',
            image:'/Images/Product6.jpg',
            image1:'/Images/Product6(1).png',
            image2:'/Images/Product6(2).png',
            price:160,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Health+ Mango-Flavour',
            category:'Energy Booster',
            image:'/Images/Product7.jpg',
            image1:'/Images/Product7(1).png',
            image2:'/Images/Product7(2).png',
            price:76,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Ajooba',
            category:'Anti Ulcer Gel',
            image:'/Images/Product8.jpg',
            image1:'/Images/Product8(1).png',
            image2:'/Images/Product8(2).png',
            price:65,
            countInStock: 0,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Health+ Lemon-Flavour',
            category:'Energy Booster',
            image:'/Images/Product9.jpg',
            image1:'/Images/Product9(1).png',
            image2:'/Images/Product9(2).png',
            price:76,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
    ],
};
export default data;