const data = {
    products:[
        {
            _id:'1',
            name:'Daksh-Prot',
            category:'Proteins',
            image:'Images/Product1.png',
            price:345,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Health+ Orange-Flavour',
            category:'Energy Booster',
            image:'Images/Product2.png',
            price:76,
            countInStock: 20,
            brand:'Sarthi Ayurveda',
            rating:4.0,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Amar Churan',
            category:'Digestive Tonic',
            image:'Images/Product3.png',
            price:124,
            countInStock: 20,
            brand:'Sarthi Ayurveda',
            rating:4.8,
            numReviews:17,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Kuffna',
            category:'Cough Remedy',
            image:'Images/Product4.png',
            price:117,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Sarliv 4G',
            category:'Digestive Tonic',
            image:'Images/Product5.png',
            price:155,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:"Happy 7 Day's",
            category:'Women Health Restorative Tonic',
            image:'Images/Product6.png',
            price:160,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'7',
            name:'Health+ Mango-Flavour',
            category:'Energy Booster',
            image:'Images/Product7.png',
            price:76,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'8',
            name:'Ajooba',
            category:'Anti Ulcer Gel',
            image:'Images/Product8.png',
            price:65,
            countInStock: 0,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {_id:'9',
            name:'Health+ Lemon-Flavour',
            category:'Energy Booster',
            image:'Images/Product9.png',
            price:76,
            countInStock: 10,
            brand:'Sarthi Ayurveda',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
    ],
};
export default data;